# Generated by Django 5.1.4 on 2025-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='budget',
            name='Subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemsitry', 'Chemistry'), ('Computer', 'Computer')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='Subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer', 'Computer')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], max_length=10),
        ),
    ]
